In [1]:
import pandas as pd
import gurobipy as gp

In [2]:
%load_ext autoreload
%autoreload 2
%aimport ModelGenerator
%aimport Methods

Set parameter Username
Set parameter LicenseID to value 2625858
Academic license - for non-commercial use only - expires 2026-02-20
Set parameter Username
Set parameter LicenseID to value 2625858
Academic license - for non-commercial use only - expires 2026-02-20
Set parameter Username
Set parameter LicenseID to value 2625858
Academic license - for non-commercial use only - expires 2026-02-20


In [3]:
mg_id = 0

#### Build Models

In [6]:
from ModelGenerator import build_models
master, subproblems, TMatrices, rVectors, Pr, Loads = build_models(mg_id=0)

Set parameter Username
Set parameter LicenseID to value 2625858
Academic license - for non-commercial use only - expires 2026-02-20


  0%|          | 0/27 [00:00<?, ?it/s]

0
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi


  0%|          | 0/27 [00:30<?, ?it/s]


KeyboardInterrupt: 

#### Load Subproblems

In [4]:
from Methods import LoadSubProblems
models, probs, TMatrices, rVectors = LoadSubProblems()

Loading Subproblems


Loading: 100%|██████████| 27/27 [00:08<00:00,  3.26it/s]


#### Solve by Callback

In [8]:
from Methods import solve_with_BD_BandB
s = 2
optimal_x, optimal_obj, x_keys, num_locations = solve_with_BD_BandB(models=models[:2], 
                                                                    probs=probs[:2], 
                                                                    TMatrices=TMatrices[:2], 
                                                                    rVectors=rVectors[:2])
optimal_x_reshaped = optimal_x.reshape(num_locations, 4)

[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0


In [10]:
import numpy as np
x_test = np.array([20, 30, 0, 0, 0, 0, 0, 0, 0, 10, 30 ,20, 0, 0, 0, 1, 0, 0, 1, 0])

### Reporting

In [11]:
from Methods import solve_subproblems
x_u_I, x_u_E = solve_subproblems(sub_models=models, 
                                 optimal_x=x_test, 
                                 x_keys=x_keys, 
                                 probs=probs, 
                                 num_locations=num_locations,
                                 mg_id=mg_id)

In [63]:
optimal_x

array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0.])