In [1]:
import pandas as pd
import gurobipy as gp

In [2]:
%load_ext autoreload
%autoreload 2
%aimport ModelGenerator
%aimport Methods

Set parameter TokenServer to value "ioml.ie.e.uh.edu"
Set parameter TokenServer to value "ioml.ie.e.uh.edu"
Set parameter TokenServer to value "ioml.ie.e.uh.edu"


In [3]:
mg_id = 0

#### Build Models

In [7]:
from ModelGenerator import build_model
build_model(mg_id=0)

Set parameter TokenServer to value "ioml.ie.e.uh.edu"


100%|██████████| 27/27 [07:48<00:00, 17.35s/it]

svmem(total=405521780736, available=396265259008, percent=2.3, used=7650013184, free=387713523712, active=8578433024, inactive=5449785344, buffers=14938112, cached=10143305728, shared=442130432, slab=705904640)
Used: 2.3% | Available: 396.27 GB


#### Load Subproblems

In [4]:
from Methods import LoadSubProblems
models, probs, TMatrices, rVectors = LoadSubProblems()

Loading Subproblems


Loading: 100%|██████████| 27/27 [00:08<00:00,  3.26it/s]


#### Solve by Callback

In [8]:
from Methods import solve_with_BD_BandB
s = 2
optimal_x, optimal_obj, x_keys, num_locations = solve_with_BD_BandB(models=models[:2], 
                                                                    probs=probs[:2], 
                                                                    TMatrices=TMatrices[:2], 
                                                                    rVectors=rVectors[:2])
optimal_x_reshaped = optimal_x.reshape(num_locations, 4)

[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0
[ 0.  0.  0. ... -0. -0. -0.]
cut added
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0


In [10]:
import numpy as np
x_test = np.array([20, 30, 0, 0, 0, 0, 0, 0, 0, 10, 30 ,20, 0, 0, 0, 1, 0, 0, 1, 0])

### Reporting

In [11]:
from Methods import solve_subproblems
x_u_I, x_u_E = solve_subproblems(sub_models=models, 
                                 optimal_x=x_test, 
                                 x_keys=x_keys, 
                                 probs=probs, 
                                 num_locations=num_locations,
                                 mg_id=mg_id)

In [63]:
optimal_x

array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0.])